export const host: string = 'https://api.themis.umb.ihojose.com:3000';

export const environment: any = {
  notification: {
    duration: 5000
  },
  api: {
    auth: `${ host }/account/auth`,
    get_accounts: `${ host }/account`,
    register: `${ host }/account`,
    get_account: `${ host }/account/{id}`,
    edit_account: `${ host }/account/{id}`,
    edit_password: `${ host }/account/password`,
    check_account: `${ host }/account/check/{username}`,
    get_sessions: `${ host }/session/{user}`,
    add_session: `${ host }/session`,
    delete_session: `${ host }/session/{id}`,
    get_history: `${ host }/history/session/{session}`,
    add_history: `${ host }/history`,
    get_roles: `${ host }/role`,
    get_role: `${ host }/role/{id}`,
    delete_role: `${ host }/role/{id}`,
    add_role: `${ host }/role`,
    edit_role: `${ host }/role/{id}`,
    add_permission: `${ host }/permission`,
    edit_permission: `${ host }/permission/{id}`,
    delete_permission: `${ host }/permission/{id}`,
    get_laws: `${ host }/law`,
    get_law: `${ host }/law/{id}`,
    add_law: `${ host }/law`,
    edit_law: `${ host }/law/{id}`,
    delete_law: `${ host }/law/{id}`,
    get_articles: `${ host }/article/{id}`,
    get_article: `${ host }/article/{id}/details`,
    add_article: `${ host }/article`,
    edit_article: `${ host }/article/{id}`,
    delete_article: `${ host }/article/{id}`,
    get_aggravating: `${ host }/aggravating/{id}`,
    get_first_aggravating: `${ host }/aggravating/first/{law}`,
    get_aggravating_list: `${ host }/aggravating`,
    get_aggravating_by_article: `${ host }/aggravating/article/{id}`,
    add_aggravating: `${ host }/aggravating`,
    edit_aggravating: `${ host }/aggravating/{id}`,
    delete_aggravating: `${ host }/aggravating/{id}`,
    add_asnwer: `${ host }/aggravating/answer`,
    edit_asnwer: `${ host }/aggravating/answer/{id}`,
    delete_asnwer: `${ host }/aggravating/answer/{id}`,
    ref_sentence: `${ host }/aggravating/answer/sentence`,
    delete_ref_sentence: `${ host }/aggravating/answer/{1}/sentence/{2}`,
    get_sentences: `${ host }/sentence`,
    get_sentence: `${ host }/sentence/{id}`,
    add_sentence: `${ host }/sentence`,
    edit_sentence: `${ host }/sentence/{id}`,
    delete_sentence: `${ host }/sentence/{id}`,
    add_verdict: `${ host }/sentence/verdict`,
    get_verdicts: `${ host }/sentence/verdict`,
    get_verdict: `${ host }/sentence/verdict/{id}`,
  }
};
